### ISSUE TITLE
New version error

### ISSUE THREAD

**Issue by juliocanares** [np-maintain/simple-recaptcha-new#2]
I updated to v1.1.0 and I'm getting this error [Error: missing-input-secret] , I tried with v1.0.0 and it works

``` javascript
var ip = req.ip, response = req.body['g-recaptcha-response'];
simple_recaptcha(global.cf.recaptcha.privateKey, ip, response, function (error) {
   if (error) console.log(error); // [Error: missing-input-secret]
});
```

**Comment by wzrdtales** [comment]
Sry for the delay, I have been sick and wasn't able to respond any soones. I will try to reproduce your issue and take a look at your PR soon.

**Comment by wzrdtales** [comment]
Ok, Ic what happened when I merged the last PR. A small simple detail I really have overseen. The plus sign. Thanks for reporting!

**Comment by wzrdtales** [comment]
Published as
- simple-recaptcha-new@1.1.1
